### ISSUE TITLE
Replace Lorem Ipsum Text & Filler Images

### ISSUE THREAD

**Issue by Septimis** [Septimis/MtnMentalHealth#7]
# Home Page

- Replace what is `Mountain Mental Health` with: `About Us`
- Replace lorem ipsum text under the header **About Us** with:

> Mountain Mental Health is an outpatient clinic serving the community by treating a wide range of mental health disorders, from mild to complex in nature. We view each person as an individual and create a plan that is unique to you and your distinct struggles. We believe that anyone who takes the path to Wellness deserves to have a voice and to be treated with respect and empowerment.

> We strive provide the best care for you, and will work closely with you, your family, and other providers or therapists to help find a successful path of treatment.

> Our Vision is to provide quality healthcare to those struggling with their mental health.

- Replace image associated with **About Us** with the image specified in the change request document.
<br>

- Add a section titled `Elevate Your Wellness: The Importance of Mental Health Treatment`
- Add text under previous title with the following:

> What about our mental health? Nearly [44 million](https://www.nami.org/Learn-More/Mental-Health-By-the-Numbers) Americans, nearly 1 in 5 adults, struggle with a mental health issue in a given year. For too long individuals who suffer from a mental health disorder have chosen to ignore their symptoms in fear of the social stigma that has persistently clung to mental illness. That has to stop.

> There is increasing awareness in the scientific community of the link between our physical health and our psychological health. Untreated mental illness has profound consequences to our health and wellbeing, including increased risk of heart disease, a weakened immune system, [reduced lifespan](https://www.bmj.com/content/345/bmj.e4933), financial instability, interpersonal problems, career fallout, and legal issues.

> The mind-body connection is real. To maximize overall health and well-being it is critical that mental health disorders be addressed and treated. Treatment of mental health conditions provides the needed support to both manage symptoms and process unresolved traumas or painful emotional events that may be contributing to the disorder. Learn about the healing options at Mountain Mental Health.

- Add the associated image for this section specified in the change request document.
<br>

- Replace the section title `What Mental Health Services Do We Provide?` with `Services offered by Mountain Mental Health`
- Replace lorem ipsum text with:

> We offer mental health services, including psychiatric assessment, diagnosing, medication management, and medical cannabis. We are also a REMS-certified treatment center offering Spravato ® (esketamine) for individuals who have treatment resistant depression 

- Replace image associated with this section with the one specified in the change request document.
<br>

- Replace the lorem ipsum text under `Virtual Appointments` with the following:

> We understand that much-needed appointments can be difficult to maintain. We offer flexibility and convenience to see your provider through live, interactive communication on any smart phone, tablet or computer. [Telemedicine](https://leesidewellness.com/telemedicine/) is the process of providing health care using video conferencing. Providing convenient, confidential and compassionate care that works around your schedule. 

<hr>

# Team Page

- Remove Karen & Ray's name from Providing Team section

> ### Spencer Lowe
>
> - Add `DNP, APRN, FNP-C, CNE, PMHNP-BC, QMP` titles
> - Add the following description:
> 
>> Dr. Spencer Lowe is an advanced practice nurse (APRN) who holds dual advanced degrees including a Doctor of Nursing Practice Degree from the University of Utah and a psychiatric mental health nurse practitioner (PMHNP) from the University of Cincinnati. He has also served as a member of the Utah Air National Guard for the last 17 years, where he is a provider in the medical group. Dr. Lowe has worked in the healthcare field since 2007 where he specialized in endocrine and transplant nursing. Dr. Lowe treats a broad range of mental health issues throughout the life span including children, adolescents, and adults. Dr. Lowe is now accepting new patients, please call our office to set up an appointment.

> ### Shane Carter
>
> - Add `APRN, PMHNP-BC, MSN-ED, QMP` titles
> - Add the following description:
>
>> Shane is an advanced practice nurse (APRN) who holds dual master's degrees as an MSN-ED, and psychiatric mental health nurse practitioner from the University of Cincinnati. Shane has worked in the medical field since 2004 and specialized in critical care nursing where he cared for his fellow veterans at the Salt Lake City Veterans Hospital. He has served in the military for 20 years and is currently a provider in the Utah Air National Guard med group. Shane treats a variety of mental health issues throughout the life span including children, adolescents, and adults. Shane is now accepting new patients, please call our office to set up an appointment.

- Add **Support Team** section
  - Add `Melissa Blair` to Support Team section
  - Add `Kristina Magleby` to Support Team section
  - Add `Jordan Young` to Support Team section
  - Add the following description to the Support Team section:

> We have a talented support team that will help you communicate with your providers, schedule and reschedule appointments, obtain medications efficiently, work with your health insurance, and assure an overall positive experience. 

<hr>

# Services Page

- Replace the text under the `Medication Management` section:

> Mountain Mental Health nurse practitioners work to assess, diagnose, and manage a variety of conditions through individualized psychotropic medication management. Psychiatric medications can treat a variety of conditions such as depression, anxiety, PTSD, ADHD, bipolar disorder, and psychotic disorders

- Replace image associated with `Medication Management` section with the one in the change request document.

- Add a section titled `Spravato ® (esketamine)` with the following description:

> Spravato® (esketamine intranasal) is a prescription, FDA-approved nasal spray made up of the chemical esketamine, which is made from ketamine, an anesthetic drug that is also used to treat depression at subanesthetic doses which is administered in our clinic. When used in conjunction with an oral antidepressant, Spravato can provide relief from treatment resistant major depression and depression with suicidal thoughts, within hours of using it.

- Add associated image in the change request document.

<br>

- Add section titled `Medical Cannabis Cards` with the following description:

> At Mountain Mental Health we strive to make the process of applying for a Utah State Medical Marijuana card as affordable, informative, and easy as possible. In person appointments are available to meet with our qualified medical providers (QMP). Our QMP's will meet with you and evaluate if you have medical conditions that qualify for medical cannabis during a short 10–15-minute visit. Once you have scheduled an appointment with us and come in for your medical marijuana evaluation, we will assist you with the entire online state application process.

- Add associated image in the change request document.

<br>

- Replace banner image with the one specified in the change request document.

**Comment by NCA-LEADER** [comment]
5 years of age and 5 years of age facts are, both stories, no insert wth pns, a tickle, non criminally rspnsible age group, yet you have held down and injctd, evn with the bullsht you have, your sck
